"""transaction_id unique per entity

Revision ID: 23783ad3c535
Revises: 977136c20ceb
Create Date: 2025-12-25 20:06:22.465892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23783ad3c535'
down_revision = '977136c20ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('transaction_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_unique_constraint('uq_entity_transaction_id', ['entity_id', 'transaction_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_entity_transaction_id', type_='unique')
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_id'))
        batch_op.alter_column('transaction_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
