"""add posted_at to transactions

Revision ID: 755a9446144d
Revises: c84d2b137411
Create Date: 2025-12-18 12:43:17.513849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755a9446144d'
down_revision = 'c84d2b137411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('posted_at')

    # ### end Alembic commands ###
