"""Add audit fields

Revision ID: 812c0a66cc61
Revises: 
Create Date: 2025-12-18 10:47:58.467313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812c0a66cc61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # --- transaction_lines ---
    with op.batch_alter_table('transaction_lines', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('created_at', sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('updated_at', sa.DateTime(), nullable=True)
        )

    # Populate existing rows
    op.execute(
        "UPDATE transaction_lines SET created_at = CURRENT_TIMESTAMP "
        "WHERE created_at IS NULL"
    )

    # Enforce NOT NULL after backfill
    with op.batch_alter_table('transaction_lines', schema=None) as batch_op:
        batch_op.alter_column(
            'created_at',
            nullable=False
        )

    # --- transactions ---
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('created_at', sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('updated_at', sa.DateTime(), nullable=True)
        )

    op.execute(
        "UPDATE transactions SET created_at = CURRENT_TIMESTAMP "
        "WHERE created_at IS NULL"
    )

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column(
            'created_at',
            nullable=False
        )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('transaction_lines', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
