"""empty message

Revision ID: 977136c20ceb
Revises: 755a9446144d
Create Date: 2025-12-23 14:26:54.670491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977136c20ceb'
down_revision = '755a9446144d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memo', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_lines', schema=None) as batch_op:
        batch_op.drop_column('memo')

    # ### end Alembic commands ###
