"""Add audit fields to transactions

Revision ID: a9d92e6172a2
Revises: 812c0a66cc61
Create Date: 2025-12-18 11:30:22.514120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d92e6172a2'
down_revision = '812c0a66cc61'
branch_labels = None
depends_on = None


def upgrade():
    # Add columns as nullable first
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.add_column(
            sa.Column('created_at', sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('updated_at', sa.DateTime(), nullable=True)
        )

    # Backfill existing rows
    op.execute(
        "UPDATE transactions "
        "SET created_at = CURRENT_TIMESTAMP "
        "WHERE created_at IS NULL"
    )

    # Enforce NOT NULL after backfill
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.alter_column(
            'created_at',
            nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('transaction_lines', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
