"""empty message

Revision ID: e62fea850d0a
Revises: b1c2d3e4f5a6
Create Date: 2026-01-01 20:39:47.998518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62fea850d0a'
down_revision = 'b1c2d3e4f5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('csv_account_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_csv_account_mappings_entity_source'))

    with op.batch_alter_table('csv_import_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_csv_import_reviews_entity_source'))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=50), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_date'))
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('code')

    with op.batch_alter_table('csv_import_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_csv_import_reviews_entity_source'), ['entity_id', 'source'], unique=False)

    with op.batch_alter_table('csv_account_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_csv_account_mappings_entity_source'), ['entity_id', 'source'], unique=False)

    # ### end Alembic commands ###
